package com.quickcart.config;
import com.quickcart.entity.*; import com.quickcart.repository.*; import org.springframework.boot.CommandLineRunner; import org.springframework.context.annotation.Bean; import org.springframework.context.annotation.Configuration; import java.util.*;
@Configuration public class SeedDataConfig {
 @Bean CommandLineRunner seed(CategoryRepository cr, ProductRepository pr){return args->{
  if(cr.count()>0)return;
  String[][] cs={{"Grocery","Daily groceries"},{"Fruits","Fresh fruits"},{"Vegetables","Fresh vegetables"},{"Dairy","Milk and dairy"},{"Meat","Fresh meat and fish"},{"Baby","Baby care"},{"Men","Men fashion"},{"Women","Women fashion"},{"Boys","Boys fashion"},{"Girls","Girls fashion"},{"Electronics","Electronics"},{"Mobiles","Mobile phones"},{"Laptops","Laptops"},{"TVs","Televisions"},{"ACs","Air conditioners"},{"Refrigerators","Refrigerators"},{"Furniture","Furniture"},{"Beds","Beds"},{"Home & Kitchen","Home and kitchen"},{"Beauty","Beauty"},{"Medicine","Health products"},{"Other","Other products"}};
  List<Category> cats=new ArrayList<>();int order=1;for(String[] c:cs)cats.add(cr.save(new Category(null,c[0],c[1],"",true,order++)));
  Map<String,Category> m=new HashMap<>();for(Category c:cats)m.put(c.getName(),c);
  Object[][] ps={
   {"Premium Basmati Rice 5 kg","Grocery","Daawat",499,599,"5 kg","rice","SMALL"},{"Whole Wheat Atta 5 kg","Grocery","Aashirvaad",285,320,"5 kg","atta","SMALL"},{"Toor Dal 1 kg","Grocery","Tata Sampann",165,190,"1 kg","dal","SMALL"},{"Sunflower Oil 1 L","Grocery","Fortune",139,165,"1 L","oil","SMALL"},{"Sugar 1 kg","Grocery","Tata",48,55,"1 kg","oil","SMALL"},{"Salt 1 kg","Grocery","Tata",24,30,"1 kg","oil","SMALL"},{"Milk 1 L","Dairy","Heritage",62,68,"1 L","milk","SMALL"},{"Farm Fresh Eggs 12","Dairy","Suguna",89,105,"12 pcs","egg","SMALL"},{"Fresh Tomatoes","Vegetables","Local Farm",42,50,"1 kg","tomato","SMALL"},{"Fresh Potatoes","Vegetables","Local Farm",38,45,"1 kg","potato","SMALL"},{"Fresh Onions","Vegetables","Local Farm",44,52,"1 kg","onion","SMALL"},{"Fresh Apples","Fruits","Fresh Farm",149,180,"1 kg","apple","SMALL"},{"Banana Robusta","Fruits","Fresh Farm",55,65,"1 dozen","banana","SMALL"},{"Alphonso Mango","Fruits","Fresh Farm",249,299,"1 kg","mango","SMALL"},{"Green Grapes","Fruits","Fresh Farm",119,145,"500 g","grapes","SMALL"},{"Chicken Curry Cut","Meat","Local Meat",249,280,"500 g","chicken","SMALL"},{"Fresh Fish","Meat","Local Fish",299,350,"500 g","fish","SMALL"},{"Baby Diapers","Baby","Pampers",699,799,"Pack","diaper","SMALL"},{"Baby Wipes","Baby","Himalaya",199,249,"Pack","diaper","SMALL"},{"Men Cotton T-Shirt","Men","QuickStyle",499,799,"1 piece","tshirt","SMALL"},{"Women Casual Dress","Women","StyleHub",899,1299,"1 piece","dress","SMALL"},{"Boys Casual T-Shirt","Boys","KidsWear",399,599,"1 piece","tshirt","SMALL"},{"Girls Frock","Girls","KidsWear",599,899,"1 piece","dress","SMALL"},{"Wireless Earbuds","Electronics","SoundPro",1299,1999,"1 unit","earbuds","SMALL"},{"Android Smartphone","Mobiles","SmartTech",14999,16999,"1 unit","mobile","MEDIUM"},{"Business Laptop 15-inch","Laptops","TechBook",54999,62999,"1 unit","laptop","MEDIUM"},{"55-inch 4K Smart TV","TVs","VisionPlus",32999,39999,"1 unit","tv","LARGE"},{"1.5 Ton Split AC","ACs","CoolAir",38999,45999,"1 unit","ac","LARGE"},{"Double Door Refrigerator","Refrigerators","FreshCool",42999,49999,"1 unit","fridge","HEAVY"},{"3-Seater Sofa","Furniture","HomeCraft",18999,22999,"1 unit","sofa","HEAVY"},{"Queen Bed","Beds","HomeCraft",24999,29999,"1 unit","bed","HEAVY"},{"Dining Chair","Home & Kitchen","HomeCraft",1499,1999,"1 unit","chair","MEDIUM"},{"Digital Thermometer","Medicine","HealthCare",149,199,"1 unit","medicine","SMALL"}
  };
  for(Object[] x:ps){String n=(String)x[0],cat=(String)x[1],brand=(String)x[2],img=(String)x[6],type=(String)x[7];double price=(double)x[3],mrp=(double)x[4];Product p=new Product(null,n,"Sample product for ZeptoPluse.",brand,m.get(cat),mrp,price,Math.round((mrp-price)*10000.0/mrp)/100.0,(String)x[5],"","",true,100,type,"assets/products/"+img+".png");pr.save(p);}
 };}
}
